# Generated by Django 5.1.7 on 2025-08-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todotask_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='user_id',
            new_name='user',
        ),
    ]
