# Generated by Django 5.1.7 on 2025-08-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_todotask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='user',
        ),
    ]
